version: '3'

vars:
  COMPOSE_FILES: --env-file .env -f docker/postgres.compose.yml

tasks:
  up:
    desc: Levanta los contenedores de frontend y PostgreSQL en segundo plano
    cmds:
      - docker compose {{.COMPOSE_FILES}} up -d
      - npm run db:generate
      - npm run db:migrate
      - npm run db:push
      - npm run db:studio & npm run dev

  down:
    desc: Detiene y elimina los contenedores y la red compartida
    cmds:
      - docker compose {{.COMPOSE_FILES}} down

  logs:
    desc: Sigue los logs combinados de ambos servicios
    cmds:
      - docker compose {{.COMPOSE_FILES}} logs -f
